DRL:
  Learn:
    actions: 2  # number of valid actions
    data_save_path: '/DRL-interpreter-model/data/flappybird/'
    action_type: 'discrete'
    state_size: 12
    action_size: 27
    reward_size: 1

DEG:
  Learn:
    name : 'icehockey'  # 'main'
    cuda : True
    max_iter: 1000000
    batch_size: 32
    print_iter : 100
    z_dim: 10  # 'dimension of the representation z'
    num_workers : 2
    dset_dir: '/Ice-hockey-data/2018-2019'
    image_type: 'origin'

  AAE:
    lr_D : 0.0002
    beta1_D : 0.0
    beta2_D : 0.9
    lr_G : 0.0002
    beta1_G : 0.5
    beta2_G : 0.9
    lr_E : 0.0002
    beta1_E : 0.5
    beta2_E : 0.9
    ckpt_dir : '/DRL-interpreter-model/DEG/AAE/flappybird/'
    output_dir: '/DRL-interpreter-model/DEG/AAE/flappybird/'
    viz_ta_iter: 10000
    ckpt_save_iter: 10000
    ckpt_load: True
    output_save: True

  FVAE:
    gamma: 6.4
    lr_VAE: 0.0001
    beta1_VAE : 0.9
    beta2_VAE : 0.999
    lr_D : 0.0001
    beta1_D : 0.5
    beta2_D : 0.9
    ckpt_save_iter: 10000
    ckpt_load: True
    output_save: True
    ckpt_dir : '/DRL-interpreter-model/DEG/FVAE/flappybird/'
    output_dir: '/DRL-interpreter-model/DEG/FVAE/flappybird/'
    viz_ta_iter: 10000

  CVAE:
    gamma: 6.4
    lr_VAE: 0.0001
    beta1_VAE : 0.9
    beta2_VAE : 0.999
    lr_D : 0.0001
    beta1_D : 0.5
    beta2_D : 0.9
    ckpt_save_iter: 10000
    ckpt_load: True
    output_save: True
    ckpt_dir : '/DRL-interpreter-model/DEG/CVAE/flappybird/'
    output_dir: '/DRL-interpreter-model/DEG/CVAE/flappybird/'
    viz_ta_iter: 10000

Mimic:
  Learn:
    cuda : True
    num_simulations: 10000001
    replay_memory_size: 10000
    episodic_sample_number: 1000  # the number of selected data points
    mcts_saved_dir: '/DRL-interpreter-model/MCTS/flappybird/saved_model'
    max_k: 10
    ignore_dim: '[3, 8, 9]'

